### ISSUE TITLE
Whitespace on UserList

### ISSUE THREAD

**Issue by thiagovice** [learn-path/learn-path#4]
There is an additional whitespace on the bottom of the UserList item on the admin dashboard item when the user has a description.

<img width="349" alt="screen shot 2018-04-09 at 10 22 01 am" src="https://user-images.githubusercontent.com/5437355/38503367-e1ea2cca-3bdf-11e8-998e-cca06773511e.png">

**Comment by otavianopires** [comment]
Issue Fixed
