### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by thiagovice** [learn-path/learn-path#5]
Currently we don't an styled Access Denied message.
To reproduce, set the user to a non-admin role and try do access the admin section.
The message Access Denied will show up.

We should create a better looking message.

<img width="724" alt="screen shot 2018-04-09 at 10 23 15 am" src="https://user-images.githubusercontent.com/5437355/38503529-52ebeb52-3be0-11e8-9bcf-09fca34db5c8.png">

**Comment by otavianopires** [comment]
Fixed. Now the text has align center and a bigger font. Also, the "Loading..."text has the same style.
