### ISSUE TITLE
Short Desc

### ISSUE THREAD

**Issue by thiagovice** [learn-path/learn-path#6]
When the user logs in for the first time the short profile looks out of place, maybe it needs a container.

<img width="1278" alt="screen shot 2018-04-09 at 10 28 16 am" src="https://user-images.githubusercontent.com/5437355/38503710-c0f2d23c-3be0-11e8-88c5-9f68865d976e.png">

**Comment by otavianopires** [comment]
Fixed, now following the same design as other forms.
